
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import VantaGlobe from "../lib/vantaGlobe";
import {
  ClerkProvider,
 
} from '@clerk/nextjs';
import NavigationMenuDemo from "../Pre-built/NavBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Background (always present on all routes) */}
          <VantaGlobe />

          {/* Foreground content */}
          <div className="relative z-10">
            <div className="flex justify-center">
              <NavigationMenuDemo />
            </div>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}

